pr: &pr {type: select, proxies: [🇭🇰 香港节点, 🇹🇼 台湾节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇺🇸 美国节点, 🔰 节点选择, 🚀 手动切换, DIRECT]}

p: &p {type: http, interval: 3600, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}

mode: rule
mixed-port: 51300
socks-port: 7898
port: 7899
allow-lan: true
log-level: info
ipv6: true
secret: '0513'
external-controller: 127.0.0.1:51225

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 11.0.0.1/16
  fake-ip-filter:
  - +.lan
  - +.local
  - +.msftconnecttest.com
  - +.msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - localhost.work.weixin.qq.com
  default-nameserver:
  - 8.8.8.8
  - 1.1.1.1
  - 223.5.5.5
  - 119.29.29.29
  nameserver:
  - https://8.8.8.8/dns-query
  - https://8.8.4.4/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  proxy-server-nameserver:
  - https://8.8.8.8/dns-query
  - https://8.8.4.4/dns-query
  - https://1.1.1.1/dns-query
  - https://1.0.0.1/dns-query
  nameserver-policy:
    geosite:private,cn,geolocation-cn:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
    geosite:google,youtube,telegram,gfw,geolocation-!cn:
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query

tun:
  stack: gvisor
  device: Meta
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  strict-route: false
  mtu: 9000
  enable: true

proxy-providers:
  🛫 我的机场:
    <<: *p
    url: "https://example.com/xxx/xxx&flag=clash"
    path: ./proxies/airport.yaml

proxy-groups:
  - {name: 🔰 节点选择, type: select, proxies: [🇭🇰 香港节点, 🇹🇼 台湾节点, 🇯🇵 日本节点, 🇸🇬 新加坡节点, 🇺🇸 美国节点, 🚀 手动切换, DIRECT]}
  - {name: 🚀 手动切换, type: select, include-all: true}

  - {name: 📲 电报消息, <<: *pr}
  - {name: 💬 OpenAi, <<: *pr}
  - {name: 🎶 网易音乐, <<: *pr}
  - {name: 🎶 Spotify, <<: *pr}
  - {name: 📹 油管视频, <<: *pr}
  - {name: 🎥 奈飞视频, <<: *pr}
  - {name: 📺 巴哈姆特, <<: *pr}
  - {name: 📺 哔哩哔哩, <<: *pr}
  - {name: 🌍 国外媒体, <<: *pr}
  - {name: 🌏 国内媒体, <<: *pr}
  - {name: Ⓜ️ 微软服务, <<: *pr}
  - {name: 🍎 苹果服务, <<: *pr}
  - {name: 🎮 游戏平台, <<: *pr}

  - {name: 🛑 广告拦截, type: select, proxies: [REJECT, DIRECT]}
  - {name: 🎯 全球直连, type: select, proxies: [DIRECT, 🔰 节点选择]}
  - {name: 🖥️ 直连软件, type: select, proxies: [🎯 全球直连]}
  - {name: 🐟 漏网之鱼, <<: *pr}

  - {name: 🇭🇰 香港节点, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)港|hk|hongkong|hong kong"}
  - {name: 🇹🇼 台湾节点, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)台|tw|taiwan"}
  - {name: 🇯🇵 日本节点, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)日本|jp|japan"}
  - {name: 🇸🇬 新加坡节点, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)新|sg|singapore"}
  - {name: 🇺🇸 美国节点, type: url-test, tolerance: 50, include-all-providers: true, filter: "(?i)美|us|unitedstates|united states"}

rule-anchor:
  classical: &classical {type: http, interval: 86400, behavior: classical, format: text}

rule-providers:
  # 若使用 ShellCrash，由于无法判断本机进程（默认 `find-process-mode: off`），需删除此条 `applications`
  applications:
    <<: *classical
    path: ./ruleset/soratanmer/applications.list
    url: "https://raw.githubusercontent.com/soratanmer/ACL4SSR/main/Clash/Ruleset/applications.list"
  BanAD:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanAD.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list"
  BanProgramAD:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanProgramAD.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list"
  BanEasyList:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanEasyList.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list"
  BanEasyListChina:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanEasyListChina.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list"
  BanEasyPrivacy:
    <<: *classical
    path: ./ruleset/ACL4SSR/BanEasyPrivacy.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list"
  LocalAreaNetwork:
    <<: *classical
    path: ./ruleset/ACL4SSR/LocalAreaNetwork.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list"
  UnBan:
    <<: *classical
    path: ./ruleset/ACL4SSR/UnBan.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
  GoogleCN:
    <<: *classical
    path: ./ruleset/ACL4SSR/GoogleCN.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list"
  SteamCN:
    <<: *classical
    path: ./ruleset/ACL4SSR/SteamCN.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list"
  OneDrive:
    <<: *classical
    path: ./ruleset/ACL4SSR/OneDrive.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list"
  Microsoft:
    <<: *classical
    path: ./ruleset/ACL4SSR/Microsoft.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list"
  Apple:
    <<: *classical
    path: ./ruleset/ACL4SSR/Apple.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list"
  Telegram:
    <<: *classical
    path: ./ruleset/ACL4SSR/Telegram.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list"
  OpenAi:
    <<: *classical
    path: ./ruleset/ACL4SSR/OpenAi.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list"
  Spotify:
    <<: *classical
    path: ./ruleset/ACL4SSR/Spotify.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Spotify.list"
  NetEaseMusic:
    <<: *classical
    path: ./ruleset/ACL4SSR/NetEaseMusic.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list"
  Epic:
    <<: *classical
    path: ./ruleset/ACL4SSR/Epic.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list"
  Origin:
    <<: *classical
    path: ./ruleset/ACL4SSR/Origin.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list"
  Sony:
    <<: *classical
    path: ./ruleset/ACL4SSR/Sony.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list"
  Steam:
    <<: *classical
    path: ./ruleset/ACL4SSR/Steam.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list"
  Nintendo:
    <<: *classical
    path: ./ruleset/ACL4SSR/Nintendo.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list"
  YouTube:
    <<: *classical
    path: ./ruleset/ACL4SSR/YouTube.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list"
  Netflix:
    <<: *classical
    path: ./ruleset/ACL4SSR/Netflix.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list"
  Bahamut:
    <<: *classical
    path: ./ruleset/ACL4SSR/Bahamut.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"
  BilibiliHMT:
    <<: *classical
    path: ./ruleset/ACL4SSR/BilibiliHMT.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list"
  Bilibili:
    <<: *classical
    path: ./ruleset/ACL4SSR/Bilibili.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list"
  ChinaMedia:
    <<: *classical
    path: ./ruleset/ACL4SSR/ChinaMedia.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list"
  ProxyMedia:
    <<: *classical
    path: ./ruleset/ACL4SSR/ProxyMedia.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list"
  ProxyGFWlist:
    <<: *classical
    path: ./ruleset/ACL4SSR/ProxyGFWlist.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
  ChinaDomain:
    <<: *classical
    path: ./ruleset/ACL4SSR/ChinaDomain.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
  ChinaCompanyIp:
    <<: *classical
    path: ./ruleset/ACL4SSR/ChinaCompanyIp.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list"
  Download:
    <<: *classical
    path: ./ruleset/ACL4SSR/Download.list
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list"

# 规则
rules:
  # 若使用 ShellCrash，由于无法判断本机进程（默认 `find-process-mode: off`），需删除此条 `RULE-SET`
  - RULE-SET,applications,🖥️ 直连软件
  - RULE-SET,BanAD,🛑 广告拦截
  - RULE-SET,BanProgramAD,🛑 广告拦截
  - RULE-SET,BanEasyList,🛑 广告拦截
  - RULE-SET,BanEasyListChina,🛑 广告拦截
  - RULE-SET,BanEasyPrivacy,🛑 广告拦截
  - RULE-SET,LocalAreaNetwork,🎯 全球直连
  - RULE-SET,UnBan,🎯 全球直连
  - RULE-SET,GoogleCN,🎯 全球直连
  - RULE-SET,OneDrive,Ⓜ️ 微软服务
  - RULE-SET,Microsoft,Ⓜ️ 微软服务
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,Telegram,📲 电报消息
  - RULE-SET,OpenAi,💬 OpenAi
  - RULE-SET,NetEaseMusic,🎶 网易音乐
  - RULE-SET,Spotify,🎶 Spotify
  - RULE-SET,Epic,🎮 游戏平台
  - RULE-SET,Origin,🎮 游戏平台
  - RULE-SET,Sony,🎮 游戏平台
  - RULE-SET,Steam,🎮 游戏平台
  - RULE-SET,Nintendo,🎮 游戏平台
  - RULE-SET,YouTube,📹 油管视频
  - RULE-SET,Bahamut,📺 巴哈姆特
  - RULE-SET,BilibiliHMT,📺 哔哩哔哩
  - RULE-SET,Bilibili,📺 哔哩哔哩
  - RULE-SET,ChinaMedia,🌏 国内媒体
  - RULE-SET,ProxyMedia,🌍 国外媒体
  - RULE-SET,ProxyGFWlist,🔰 节点选择
  - RULE-SET,ChinaDomain,🎯 全球直连
  - RULE-SET,ChinaCompanyIp,🎯 全球直连
  - RULE-SET,Download,🎯 全球直连
  - GEOIP,CN,🎯 全球直连
  - MATCH,🐟 漏网之鱼
